# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distMat <- function(nn, dd, ZZ) {
    .Call(`_LLSMSR_distMat`, nn, dd, ZZ)
}

FullLogLikCOVSR <- function(YY, ZZ, XX, Beta, SS, RR, intercept, nn, dd, pp) {
    .Call(`_LLSMSR_FullLogLikCOVSR`, YY, ZZ, XX, Beta, SS, RR, intercept, nn, dd, pp)
}

likelihoodiCOVSR <- function(ii, dd, nn, pp, Yt, Xt, Zt, SS, RR, intercept, Beta) {
    .Call(`_LLSMSR_likelihoodiCOVSR`, ii, dd, nn, pp, Yt, Xt, Zt, SS, RR, intercept, Beta)
}

rcpp_hello_world <- function() {
    .Call(`_LLSMSR_rcpp_hello_world`)
}

